[package]
name = "pair_adjacent_violators"
version = "0.1.0"
authors = ["Ian Clarke <ian.clarke@gmail.com>"]
edition = "2018"
license-file = "LICENSE"

[lib]
name = "pair_adjacent_violators"
path = "src/lib.rs"

[dependencies]
ordered-float = "2.1.1"
