[package]
name = "pav_regression"
version = "0.1.0"
authors = ["Ian Clarke <ian@locut.us>"]
edition = "2018"
license-file = "LICENSE"

[lib]
name = "pav_regression"
path = "src/lib.rs"

[dependencies]
ordered-float = "2.1.1"
